services:
    _defaults:
        autoconfigure: true

    MetaModels\CoreBundle\Controller\ContentElement\ItemListController:
        arguments:
            - '@metamodels.factory'
            - '@metamodels.filter_setting_factory'
            - '@metamodels.render_setting_factory'
            - '@event_dispatcher'
            - '@MetaModels\Filter\FilterUrlBuilder'
