language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"

env:
 - CONTAO_VERSION=~4.4.0

sudo: false

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core-bundle $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

# Reverted caching due to travis bug travis-ci/travis-ci#4393
#cache:
#  directories:
#    - vendor
