language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
env:
    global:
    matrix:
        - CONTAO_VERSION=~2.11
        - CONTAO_VERSION=~3.1
        - CONTAO_VERSION=~3.2
        - CONTAO_VERSION=~3.3

install:
    - composer require contao/core $CONTAO_VERSION --prefer-dist --dev
    - composer install --prefer-dist --dev

script: ant -keep-going

branches:
  only:
    - tng

matrix:
  allow_failures:
    - env: CONTAO_VERSION=~3.3
