language: php
 
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"

env:
  - CONTAO_VERSION=~3.5.0

sudo: false
 
before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core $CONTAO_VERSION --no-update
  # We have to supply the branch alias here again as travis checks out a commit hash and therefore destroys the
  # circular dependency metamodels/base-unit-tests -> metamodels/core -> metamodels/base-unit-tests.
  - >
    if [ "x${TRAVIS_TAG}" != "x" ]; then
      COMPOSER_ROOT_VERSION=${TRAVIS_TAG} travis_retry composer update --prefer-dist --no-interaction;
    else
      COMPOSER_ROOT_VERSION=$([[ ${TRAVIS_BRANCH} =~ hotfix/([0-9.]+-(alpha|beta|rc)[0-9]+) ]] \
        && echo ${BASH_REMATCH[1]} \
        || echo dev-${TRAVIS_BRANCH}) \
        travis_retry composer update --prefer-dist --no-interaction;
    fi

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

# This used to cause corruption due to travis bug travis-ci/travis-ci#4393 - hopefully it works out now.
cache:
  directories:
    - vendor
